FROM quay.io/astronomer/astro-runtime:12.1.0

ENV AIRFLOW_VAR_RONALDO_VAR1='variavel_env'
ENV AIRFLOW_VAR_RONALDO_JSON_VAR1 = '{"key1":"value1", "key2":"value2"}'

ENV AIRFLOW_CONN_MY_PROD_DATABAS='{\
    "conn_type": "teste",\
    "description": "teste",\
    "host": "teste",\
    "port": 0,\
    "schema": "teste",\
    "extra": "teste",\
    "password": "teste"\
    }'
